spring:
  application:
    name: gateway   # 网关服务名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用基于 Eureka 的动态路由
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            # 路由规则 1: 请求 /serviceA/** 路由到 Eureka 注册的服务A
            - id: api
              uri: lb://api  # Eureka 中注册的服务 A 名称
              predicates:
                - Path=/api/**   # 匹配以 /serviceA/** 开头的路径

            # 路由规则 2: 请求 /serviceB/** 路由到 Eureka 注册的服务B
            - id: admin
              uri: lb://admin  # Eureka 中注册的服务 B 名称
              predicates:
                - Path=/admin/**   # 匹配以 /serviceB/** 开头的路径
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
