spring:
  application:
    name: eureka-server
server:
  port: 8761
aot:
  enabled: false
eureka:
  client:
    register-with-eureka: false  # Eureka Server 不需要向自己注册
    fetch-registry: false        # Eureka Server 不需要从其他注册中心拉取服务
  server:
    enable-self-preservation: false  # 禁用自我保护模式，服务故障时不会立即从注册表中删除服务
