services:

  mysql56:
    image: mysql:5.6
    container_name: mysql56
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: 123456
    ports:
      - 3307:3306
    volumes:
      - ./mysql56/data:/var/lib/mysql
      - ./mysql56/conf:/etc/mysql/conf.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  # auth:
  #   image: io.sf.modules/auth:0.0.1-SNAPSHOT
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: auth
  #   ports:
  #     - 8080:8080
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql56:3306/auth?useSSL=false&serverTimezone=UTC
  #     SPRING_DATASOURCE_USERNAME: auth
  #     SPRING_DATASOURCE_PASSWORD: 123456
  #     SPRING_REDIS_HOST: redis
  #     SPRING_REDIS_PORT: 6379
  #   depends_on:
  #     - mysql56
  #     - redis